site_name: TARS
site_url: https://rex688-png.github.io/TARS/
repo_url: https://github.com/rex688-png/TARS

theme:
    name: material
    custom_dir: docs/overrides
    palette:
        scheme: slate
        primary: orange
        accent: cyan

markdown_extensions:
    - attr_list: {}
    - admonition: {}
    - markdown.extensions.tables: {}
    - pymdownx.details: {}
    - pymdownx.magiclink: {
          "repo_url_shortener": True,
          "repo_url_shorthand": True,
          "provider": "github",
          "user": "rex688-png",
          "repo": "TARS"
      }
    - pymdownx.betterem: {}
    - pymdownx.tilde: {
          "subscript": False
      }
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist: {}
    - pymdownx.superfences: {}
